import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

const Home: NextPage = () => {
  useEffect(() => {
    fetch('/greeting', { method: 'GET' })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hey! Looks like you&apos;re using MSW... Very naice! 👏 </h1>
    </div>
  )
}

export default Home
